function [net_xy2z, net_z2y, net_x2z, net_x2y, net_cnn, net_cls, params, t, fname] = ...
    demo_dcgm(dataset, optgpu, dotest, split, imsize, do_recurrent, droprate, nettype, ...
    numft_cls, nsample, alpha, lr, lr_decay, l2reg, dropout, ...
    maxiter, saveiter, batchsize, dosample, std_init)

[net_xy2z, net_z2y, net_x2z, net_x2y, net_cnn, net_cls, params, t, fname] = ...
    dcgm(dataset, optgpu, dotest, split, imsize, do_recurrent, ...
    droprate, nettype, numft_cls, nsample, alpha, lr, lr_decay, l2reg, ...
    dropout, maxiter, saveiter, batchsize, dosample, std_init);

return;